---
- hosts: all
  become: true
  tasks:

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - docker-ce=5:24.0.7-1~ubuntu.20.04~focal
      - docker-ce-cli=5:24.0.7-1~ubuntu.20.04~focal
      - containerd.io=1.6.24-1

  - name: Check if the file exists
    ansible.builtin.stat:
      path: /etc/containerd/config.toml
    register: containerd_config
    ignore_errors: true

  #Workaround - Kubernetes latest versions have not written supported CRI API's for docker
  - name: Ensure the line is present in the file
    lineinfile:
      path: /etc/containerd/config.toml
      regexp: '^disabled_plugins = \["cri"\]'
      line: 'disabled_plugins = [""]'
      backrefs: yes
    when: containerd_config.stat.exists

  - name: Restart containerd.io
    service:
      name: containerd
      daemon_reload: yes
      state: restarted

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    loop:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes packages
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - kubelet=1.28.2-00
      - kubeadm=1.28.2-00
      - kubectl=1.28.2-00

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
      create: yes

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name kubem00 --pod-network-cidr=192.168.0.0/16
    ignore_errors: true

  - name: Create .kube dir for vagrant user
    file:
      path: /home/vagrant/.kube
      state: directory
      owner: vagrant
      group: vagrant
      mode: '0755'

  - name: Copy admin.conf to vagrant user's kubeconfig
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant
      mode: '0644'
      remote_src: true

  - name: Change ownership of kubeconfig file to vagrant user
    file:
      path: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant

  - name: Install tigera calico operator
    become: false
    command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/tigera-operator.yaml
    ignore_errors: true
    
  - name: Install calico pod network
    become: false
    command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/custom-resources.yaml
    ignore_errors: true

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Save join command to temp directory
    ansible.builtin.copy:
      content: "{{ join_command.stdout_lines[0] }}"
      dest: /tmp/join-command

  - name: Copy join command to local machine
    ansible.builtin.fetch:
      src: "/tmp/join-command"
      dest: ./.cluster

  ##ARGOCD Deployment

  - name: Install pip3
    apt: 
      name: python3-pip
      state: present

  - name: Install bottle python package on version 0.11
    ansible.builtin.pip:
      name: "{{ item }}"
    loop:
      - PyYAML
      - openshift
      - ansible
    
  - name: Create ArgoCD namespace
    kubernetes.core.k8s:
      kind: namespace
      name: argocd
      state: present
    become: false

  - name: Download ArgoCD deployment manifest
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      dest: ~/argocd_install.yaml
      mode: '0664'
    become: false

  - name: Apply ArgoCD deployment manifest
    kubernetes.core.k8s:
      src: ~/argocd_install.yaml
      apply: true
      namespace: argocd
      state: present
    become: false
